# Generated by Django 4.2.16 on 2024-11-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
