# Generated by Django 4.2.16 on 2024-11-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0002_purchase_category_purchase_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.CharField(blank=True, choices=[('1', '카테고리 1'), ('2', '카테고리 2'), ('3', '카테고리 3'), ('4', '카테고리 4'), ('5', '카테고리 5'), ('6', '카테고리 6'), ('7', '카테고리 7'), ('8', '카테고리 8'), ('9', '카테고리 9'), ('10', '카테고리 10'), ('11', '카테고리 11'), ('12', '카테고리 12')], max_length=2, null=True),
        ),
    ]
