# Generated by Django 4.2.16 on 2024-11-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0003_alter_purchase_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.CharField(blank=True, choices=[('10s', '10대'), ('20s', '20대'), ('30s', '30대'), ('40s', '40대'), ('50s+', '50대 이상')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남'), ('F', '녀')], max_length=1, null=True),
        ),
    ]
