# Generated by Django 4.2.16 on 2024-11-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0004_customer_age_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남'), ('F', '여\x1e')], max_length=1, null=True),
        ),
    ]
