# Generated by Django 4.2.16 on 2024-11-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0005_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.CharField(blank=True, choices=[('10대', '10대'), ('20대', '20대'), ('30대', '30대'), ('40대', '40대'), ('50대 이상+', '50대 이상')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('남', '남'), ('여', '여')], max_length=1, null=True),
        ),
    ]
